# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: cd weblogic10.3.6/docker-generator/ && go build .

    - name: List files
      run: ls -lha weblogic10.3.6/docker-generator/

    - name: Create a Release of commit
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ github.token }}
        automatic_release_tag: latest
        prerelease: false
        title: weblogic-docker
        files: |
          LICENSE
          */*.sh
